# Generated by Django 4.1 on 2022-09-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="isim",
                        db_index=True,
                        default="standart ürün",
                        editable=False,
                        help_text="ürün ismi için tam açıklayıcı metin",
                        max_length=100,
                        null=True,
                        verbose_name="ürün ismi",
                    ),
                ),
                (
                    "content",
                    models.TextField(max_length=500, verbose_name="ürün acıklamasi"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "stock_count",
                    models.PositiveSmallIntegerField(verbose_name="stok adedi"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ürün fiyatı"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={"db_table": "urunler",},
        ),
    ]
