# Generated by Django 4.1 on 2022-09-30 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_alter_product_name_gamecompany_bookcompany"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("page_count", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Intro",
            fields=[
                (
                    "book_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="learning.book",
                    ),
                ),
                ("content", models.TextField()),
            ],
            bases=("learning.book",),
        ),
    ]
