# Generated by Django 4.1 on 2022-09-30 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("learning", "0005_proxybook"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                ("address", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="bookcompany", name="author",),
        migrations.RemoveField(model_name="gamecompany", name="author",),
        migrations.RemoveField(model_name="intro", name="book_ptr",),
        migrations.DeleteModel(name="ProxyBook",),
        migrations.DeleteModel(name="Book",),
        migrations.DeleteModel(name="BookCompany",),
        migrations.DeleteModel(name="GameCompany",),
        migrations.DeleteModel(name="Intro",),
    ]
