# Generated by Django 4.1 on 2022-10-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_userdetail_remove_bookcompany_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
